---
  - name: Config Web VM with Docker
    hosts: webservers
    become: true
    tasks:

  - name: Uinstall apache2
    apt
      name: apache2
      state: absent

  -  name: Install docker.io
     apt:
       update_cache: yes
       name: docker.io
       state: present

   - name: Install pip3
     apt:
      name: python3-pip
      state: present

 - name: Install Python Docker Module
   pip:
     name: docker
     state: present

  - name: download and lauch a docker web container
    docker_container:
      name:dvwa
      image:cyberxsecurity/dvwa
      state:started
      resart_policy: always 
      publish_ports: 80:80

  - name: enable docker service
    systemd:
      name: docker
      enabled: yes
